### ISSUE TITLE
Cannot change delimiter, but my output needs to include {{ and }}

### ISSUE THREAD

**Issue by emayssat** [tests-always-included/mo#33] opened 2019-08-17 00:31 UTC
Hello,
I am using EKS and am trying to generate in shell a kubernetes config-map.
The final config-map document should be formatted as the following
https://eksworkshop.com/intro_to_rbac/map_iam_user_to_k8s_user/#map-the-user-1
In short, the final output needs to include the mustache delimiter.

Is there a way configure the template to prevent he replacement of the {{EC2PrivateDNSName}}  text?

**Comment by fidian** [comment] 2019-08-22 21:00
In short, no. One can not configure the template nor change the delimiters that are used within `mo`. You can, however, define environment variables and reference those, like the example committed in 3828588. This method does not work for functions because the output of a function is parsed as a mustache template.

**Comment by fidian** [comment] 2019-09-21 00:22
Closing. No response, so I hope the issue is resolved.

**Closed by fidian** 2019-09-21 00:22 UTC
