### ISSUE TITLE
Not responding on a not so complex html file 

### ISSUE THREAD

**Issue by WuMingIT** [tests-always-included/mo#69] opened 2023-11-01 06:40 UTC
Environment is macOS 10.13.6

File is a single A4 page with simple content exported from .odt to .html with LibreOffice. File does include a base64 encoded, small image. 

`KEYWORD=word mo file.html`  hangs and returns nothing. Activity Monitor shows constant activity within bash. 

To complete the picture mustache for Ruby on the same file returns an error about parsing .json. A separate issue that has been reported already.

**Comment by fidian** [comment] 2023-11-09 19:59
Are you able to share the file or a similar one that creates the same problem?

**Comment by fidian** [comment] 2023-11-14 13:31
Could you provide a way to reproduce the slowness? I would like to see if there is anything that could be done. I've regularly handled files larger than 15k and the number of variables doesn't impact the speed.

As for JSON templates or YAML templates, I am uncertain what you are talking about. `mo` can work with a JSON/YAML/HTML/TXT/whatever template file. If you're saying that `mo` can't get variables from JSON/YAML, then would you suggest a way to improve the documentation? The help for the command says the following.

```
   -s=FILE, --source=FILE
         Load FILE into the environment before processing templates.
         Can be used multiple times.
```

Lastly, the comment about global shell vars isn't entirely accurate, as you can see from the above argument to `mo`. You could define a file with your 15 variables.

**Comment by WuMingIT** [comment] 2023-11-15 10:33
> Could you provide a way to reproduce the slowness? I would like to see if there is anything that could be done. I've regularly handled files larger than 15k and the number of variables doesn't impact the speed.

It's a business file so I can not share it. When have time will try to scramble it.

Just tried with [Ruby mustache](https://github.com/mustache/mustache) cli and works:

```
time mustache values.json complex.html
...
real	0m1.171s
user	0m0.551s
sys	0m0.250s
```
[GNU Recutils](https://www.gnu.org/software/recutils/manual/html_node/Generating-Reports.html#Generating-Reports) are faster:

```
time recsel values.rec | recfmt -f complex.html
...
real	0m0.136s
user	0m0.050s
sys	0m0.055s
```

mo instead hangs and had to stop it with ctrl+x+c:

```
time NAME="TEST" mo complex.html 
^X^C^X^C
^X^C

real	0m32.907s
user	0m32.670s
sys	0m0.120s
```

> If you're saying that mo can't get variables from JSON/YAML, then would you suggest a way to improve the documentation?

This is what intended to say. I would add to the description "FILE with the format of bash .env files". This way it is clear (to me at least) it doesn't expect .json or .yaml for defining values.

**Comment by fidian** [comment] 2023-11-16 22:07
I've updated the help and added a bit that the file must be a shell script.

Any word on getting an obfuscated version of the HTML? One thing you could do is replace everything outside of braces with any other character, such as "." - the parser doesn't do anything special outside of braces.

**Comment by fidian** [comment] 2023-11-20 13:35
I understand that sending work-related templates discloses information that people would rather keep private. If you are ever able to send me the file, you are welcome to message me directly at fidian@rumkin.com or include it in a new defect. Having a really large template that parses slowly seems like something I would want to work on.

I do admit, using Bash to interpret a template is not the fastest solution in the world, but it shouldn't have taken so long that you'd give up on it working.

Closing because there's nothing more that can be done at this stage.

**Closed by fidian** 2023-11-20 13:35 UTC

**Comment by fidian** [comment] 2024-03-28 03:05
I'm pretty sure that #71 is directly related to this issue. I wish my testing earlier had found the problem.
